### ISSUE TITLE
Grails 3.3

### ISSUE THREAD

**Issue by piperpilot** [tombdean/grails-runtime-logging#2]
Any chance you have gotten this to work in Grails 3.3 with logback instead of log4j?

**Comment by tombdean** [comment]
Sorry, I was let go from the company where I worked that used grails in Feb 2016.  I haven't looked at this since that time, and probably won't again unless I get back to using grails for work.  Sorry.

**Comment by piperpilot** [comment]
Hi Tom,

I have a working version for Grails 3.  is there a way I can join this repo to add the commit, or if I create a pull request, would you consider adding it?

Thanks

**Comment by tombdean** [comment]
Hi Curtis,
If you create a pull request I'll approve it.  I have no way to test it at this point, but if you think it works I'm okay with it. 
Thanks. 
Tom


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Curtis Pope <notifications@github.com> Date: 2/21/18  7:26 PM  (GMT-05:00) To: tombdean/grails-runtime-logging <grails-runtime-logging@noreply.github.com> Cc: Tom Dean <tdean@one.net>, State change <state_change@noreply.github.com> Subject: Re: [tombdean/grails-runtime-logging] Grails 3.3 (#2) 
Hi Tom,
I have a working version for Grails 3.  is there a way I can join this repo to add the commit, or if I create a pull request, would you consider adding it?
Thanks

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tombdean/grails-runtime-logging","title":"tombdean/grails-runtime-logging","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tombdean/grails-runtime-logging"}},"updates":{"snippets":[{"icon":"PERSON","message":"@piperpilot in #2: Hi Tom,\r\n\r\nI have a working version for Grails 3.  is there a way I can join this repo to add the commit, or if I create a pull request, would you consider adding it?\r\n\r\nThanks"}],"action":{"name":"View Issue","url":"https://github.com/tombdean/grails-runtime-logging/issues/2#issuecomment-367525290"}}}
